apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: weather.local-demo
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weather
            port:
              number: 3000

