apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: weather
  name: weather
spec:
  template:
    spec:
      containers:
      - image: koios-services-weather
        name: services-weather
        imagePullPolicy: Never