apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: weather
  name: weather
spec:
  replicas: 2
  selector:
    matchLabels:
      name: weather
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: weather
    spec:
      containers:
      - image: microservice-monorepo-services-weather
        name: services-weather
        env:
          - name: ENVIRONMENT
            value: development
          - name: JWT_SECRET_TOKEN
            value: "some secret value"
          - name: DB_HOST
            value: mongo
          - name: DB_PORT
            value: "27017"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: DB_NAME
            value: /test
          - name: MQ_URL
            value: guest:guest@$(RABBITMQ_SERVICE_HOST):$(RABBITMQ_SERVICE_PORT)
          - name: MQ_EXCHANGE
            value: sensor-data
        ports:
        - containerPort: 3000
          protocol: TCP