apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-admin
  labels:
    app: mongo-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-admin
  template:
    metadata:
      labels:
        app: mongo-admin
    spec:
      containers:
      - name: mongo-admin
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongo