openapi: 3.0.3
info:
  title: WeatherAPI
  version: 1.0.0
  description: ""
paths:
  /hello:
    post:
      summary: ""
      operationId: WeatherAPI_SayHello
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SayHelloRequest"
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SayHelloResponse"
  /current:
    get:
      summary: ""
      operationId: WeatherAPI_GetCurrentWeather
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCurrentWeatherResponse"
components:
  schemas:
    SayHelloRequest:
      properties:
        name:
          type: string
          description: ""
      description: ""
    SayHelloResponse:
      properties:
        response:
          type: string
          description: ""
      description: ""
    GetCurrentWeatherRequest:
      properties: {}
      description: ""
    GetCurrentWeatherResponse:
      properties:
        f:
          type: number
          description: ""
        c:
          type: number
          description: ""
      description: ""
